name = "0g0-id-admin"
main = "src/index.ts"
compatibility_date = "2024-11-01"

routes = [
  { pattern = "admin.0g0.xyz", custom_domain = true }
]

[assets]
directory = "./public"

[vars]
IDP_ORIGIN = "https://id.0g0.xyz"

[[services]]
binding = "IDP"
service = "0g0-id"
