name = "0g0-id"
main = "src/index.ts"
compatibility_date = "2024-11-01"
workers_dev = false

[observability.logs]
enabled = true
invocation_logs = true

routes = [
  { pattern = "id.0g0.xyz", custom_domain = true }
]

[vars]
IDP_ORIGIN = "https://id.0g0.xyz"
USER_ORIGIN = "https://user.0g0.xyz"
ADMIN_ORIGIN = "https://admin.0g0.xyz"

[[d1_databases]]
binding = "DB"
database_name = "0g0-id-db"
database_id = "f13d6e85-7a42-463f-b07e-5201423dc840"
migrations_dir = "../../migrations"

[[unsafe.bindings]]
name = "RATE_LIMITER_AUTH"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 20, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_EXTERNAL"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 200, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_TOKEN"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 30, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_DEVICE_VERIFY"
type = "ratelimit"
namespace_id = "1004"
simple = { limit = 10, period = 60 }
