name = "0g0-id-user"
main = "src/index.ts"
compatibility_date = "2024-11-01"
workers_dev = false

[observability.logs]
enabled = true
invocation_logs = true

routes = [
  { pattern = "user.0g0.xyz", custom_domain = true }
]

[assets]
directory = "./public"

[vars]
IDP_ORIGIN = "https://id.0g0.xyz"
SELF_ORIGIN = "https://user.0g0.xyz"

[[services]]
binding = "IDP"
service = "0g0-id"
