import { lstatSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { INTERNAL_OPENAPI } from "../workers/id/src/routes/openapi/internal-spec.ts";
import { EXTERNAL_OPENAPI } from "../workers/id/src/routes/openapi/external-spec.ts";
import { openApiToMarkdown, type OpenApiSpec } from "../workers/id/src/routes/openapi/markdown.ts";

export const REFERENCE_FILES = ["id-internal.md", "id-external.md"] as const;
const REPO_ROOT = join(__dirname, "..");

/** Load source modules locally. No HTTP requests, Worker bindings, or credentials. */
export function renderApiReferences(
  internal: OpenApiSpec = INTERNAL_OPENAPI,
  external: OpenApiSpec = EXTERNAL_OPENAPI,
): Record<(typeof REFERENCE_FILES)[number], string> {
  const render = (spec: OpenApiSpec, source: string, html: string): string =>
    [
      "<!-- Generated by scripts/generate-api-reference.ts. Do not edit. -->",
      "",
      `一次ソース: [${source}](../../workers/id/src/routes/openapi/${source})`,
      "更新: `vp run docs:api:generate` / 確認（書き込みなし）: `vp run docs:api:check`",
      "",
      openApiToMarkdown(spec, html),
    ].join("\n");
  // Render and validate both specs before generating either file.
  return {
    "id-internal.md": render(internal, "internal-spec.ts", "https://id.0g0.xyz/docs"),
    "id-external.md": render(external, "external-spec.ts", "https://id.0g0.xyz/docs/external"),
  };
}

function safePath(path: string, directory: boolean): boolean {
  try {
    const stat = lstatSync(path);
    if (
      stat.isSymbolicLink() ||
      (directory ? !stat.isDirectory() : !stat.isFile() || stat.nlink !== 1)
    ) {
      throw new Error(`Unsafe generated-reference path: ${path}`);
    }
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}

/** Fixed filenames only; check mode never creates directories or writes files. */
export function syncApiReferences(
  mode: "generate" | "check",
  root: string = REPO_ROOT,
  references = renderApiReferences(),
): string[] {
  const docs = join(root, "docs");
  const output = join(docs, "generated");
  const docsExists = safePath(docs, true);
  const outputExists = docsExists && safePath(output, true);
  // Validate all output paths before any write, even when files already match.
  const exists = REFERENCE_FILES.map((file) => outputExists && safePath(join(output, file), false));
  const stale = REFERENCE_FILES.filter(
    (file, index) =>
      !exists[index] || readFileSync(join(output, file), "utf8") !== references[file],
  );
  if (mode === "generate" && stale.length) {
    if (!outputExists) mkdirSync(output, { recursive: true });
    for (const file of stale)
      writeFileSync(join(output, file), references[file], { encoding: "utf8", flag: "w" });
  }
  return stale.map((file) => `docs/generated/${file}`);
}

export function runApiReferenceCli(args: string[]): number {
  if (args.length !== 1 || !["--generate", "--check"].includes(args[0])) {
    console.error("Usage: node --import tsx scripts/generate-api-reference.ts --generate|--check");
    return 2;
  }
  const mode = args[0] === "--check" ? "check" : "generate";
  try {
    const stale = syncApiReferences(mode);
    if (mode === "check" && stale.length) {
      console.error(
        `Generated API references are stale or missing:\n${stale.join("\n")}\nRun: vp run docs:api:generate`,
      );
      return 1;
    }
    console.log(
      mode === "check"
        ? "Generated API references are current (read-only check)."
        : `Generated API references: ${stale.length} file(s) updated.`,
    );
    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (require.main === module) {
  process.exitCode = runApiReferenceCli(process.argv.slice(2));
}
